name: Build and deploy Node.js app to Azure Web App - divion-preview-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
        env:
          NODE_ENV: production

      - name: Prepare production deployment
        run: |
          rm -rf .git .github tests coverage .next/cache
          mkdir -p deployment
          cp -r .next node_modules public src package.json package-lock.json next.config.mjs deployment/

      - name: Zip artifact for deployment
        working-directory: deployment
        run: zip -r ../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip release
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62324234F0814502854E79AE3E4BAE87 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_591D887B27B64ABB9C94D0989D2069CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_002836D22AE14E00876823E9C3B6324F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'divion-preview-app'
          package: .
