# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - divion-preview-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm' # Add caching to speed up builds

      - name: npm install and build
        run: |
          npm ci # Use ci instead of install for more reliable builds
          npm run build
        env:
          NODE_ENV: production # Ensure production build

      - name: Prepare production deployment
        run: |
          # Remove dev dependencies after build
          npm ci --production
          # Remove unnecessary files
          rm -rf .git .github tests coverage .next/cache
          # Keep only what's needed
          mkdir -p deployment
          cp -r .next package.json package-lock.json next.config.js public node_modules deployment/
          
      - name: Zip artifact for deployment (optimized)
        working-directory: deployment
        run: zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62324234F0814502854E79AE3E4BAE87 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_591D887B27B64ABB9C94D0989D2069CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_002836D22AE14E00876823E9C3B6324F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'divion-preview-app'
          slot-name: 'Production'
          package: release.zip